### ISSUE TITLE
Linux下插件资源路径识别有误

### ISSUE THREAD

**Issue by PackageInstaller** [Yuri-YuzuChaN/nonebot-plugin-maimaidx#1]
![image](https://github.com/Yuri-YuzuChaN/nonebot-plugin-maimaidx/assets/80018096/c0cdd9f0-2794-4b28-acbe-b07eca33b97e)
如图，将static解压后放在 **/home/Neko/zhenxun_bot/data/maimai** 下

![image](https://github.com/Yuri-YuzuChaN/nonebot-plugin-maimaidx/assets/80018096/bca9a7ba-76ba-42f3-a580-e1637b6ff95c)
再在env中配置资源路径如图所示

![image](https://github.com/Yuri-YuzuChaN/nonebot-plugin-maimaidx/assets/80018096/2f6d639d-7276-45de-bd36-7ada293f720f)
使用 **今日舞萌** 指令会报文件路径错误

**Comment by Yuri-YuzuChaN** [comment]
怎么你的 `json` 会生成在 `static` 外面

**Comment by PackageInstaller** [comment]
> 怎么你的 `json` 会生成在 `static` 外面

我也想知道，但是它就是生成到外面了

**Comment by Yuri-YuzuChaN** [comment]
已修复

**Comment by PackageInstaller** [comment]
> 已修复

git pull更新并重启bot后

再使用今日萌舞指令，gocq端会出现巨长的警告
![image](https://github.com/Yuri-YuzuChaN/nonebot-plugin-maimaidx/assets/80018096/24b2db17-673b-452d-84fd-049eccb52db8)

![image](https://github.com/Yuri-YuzuChaN/nonebot-plugin-maimaidx/assets/80018096/d330022f-9a87-466d-828d-a823228e4061)

Bot端
![image](https://github.com/Yuri-YuzuChaN/nonebot-plugin-maimaidx/assets/80018096/b27570f6-b24b-48f0-9b27-2f24ae5c75ec)

**Comment by Yuri-YuzuChaN** [comment]
已修复

**Comment by PackageInstaller** [comment]
Okay
