### ISSUE TITLE
建议：关于资源包

### ISSUE THREAD

**Issue by TTsdzb** [Yuri-YuzuChaN/nonebot-plugin-maimaidx#11]
一定有人会解压的时候不注意导致解压出来多套一层 `static` 文件夹，导致找不到文件。

可以给 zip 改个别的名字，这样解压出来多套的文件夹就是那个别的名字。只要按文档所述保证解压出来是 `static` 就可以了。

**Comment by Yuri-YuzuChaN** [comment]
无论是解压到当前文件夹或者是解压到 `static\` 都是 `static`

**Comment by TTsdzb** [comment]
对于 Winrar 和 7z，解压到 static 都会导致实际的 `static` 文件夹被套在另一个也叫 static 的文件夹里。有的软件（例如 Bandizip）有智能解压功能，但这并不能代表所有的用户都使用这些软件。

**Comment by Yuri-YuzuChaN** [comment]
行吧，后续更新再改名了
