### ISSUE TITLE
ginfo 功能无法使用

### ISSUE THREAD

**Issue by Apple-QAQ** [Yuri-YuzuChaN/nonebot-plugin-maimaidx#19]
报错如下

<img width="561" alt="image" src="https://github.com/Yuri-YuzuChaN/nonebot-plugin-maimaidx/assets/88485487/2d3a07dc-90af-4282-922f-a49a36472b21">

**Comment by Yuri-YuzuChaN** [comment]
已重新打包静态文件

**Comment by Apple-QAQ** [comment]
![image](https://github.com/Yuri-YuzuChaN/nonebot-plugin-maimaidx/assets/88485487/0d48d2b5-e7eb-4400-a840-d395cf7ccbf8)


怎么字体全部变成黑色方块了
