### ISSUE TITLE
winserver2019使用帮助指令提示图片已过期

### ISSUE THREAD

**Issue by ABKQPO** [Yuri-YuzuChaN/nonebot-plugin-maimaidx#2]
请问
@manual.handle()
async def _():
    await manual.finish(MessageSegment.image(f'file:///{Root / "maimaidxhelp.png"}'), reply_message=True)
这段代码指向的图片在哪里

**Comment by Yuri-YuzuChaN** [comment]
模块包内

**Comment by ABKQPO** [comment]
图片过期要如何处理

**Comment by Yuri-YuzuChaN** [comment]
发log

**Comment by ABKQPO** [comment]
10-15 22:37:21 [DEBUG] nonebot | Running PostProcessors...
10-15 22:37:23 [INFO] nonebot_plugin_arktools | ===== ARKNIGHTS-SQLITE CONNECTED.
10-15 22:37:23 [INFO] nonebot_plugin_arktools | ##### ARKNIGHTS-SQLITE DATA ALL INITIATING ...
10-15 22:37:23 [INFO] nonebot_plugin_arktools |         - BuildingBuff data already initiated.
10-15 22:37:23 [INFO] nonebot_plugin_arktools |         - Character data already initiated.
10-15 22:37:23 [INFO] nonebot_plugin_arktools |         - Constance data already initiated.
10-15 22:37:23 [INFO] nonebot_plugin_arktools |         - Equip data already initiated.
10-15 22:37:23 [INFO] nonebot_plugin_arktools |         - GachaPool data already initiated.
10-15 22:37:23 [INFO] nonebot_plugin_arktools |         - HandbookInfo data already initiated.
10-15 22:37:23 [INFO] nonebot_plugin_arktools |         - HandbookStage data already initiated.
10-15 22:37:23 [INFO] nonebot_plugin_arktools |         - Item data already initiated.
10-15 22:37:23 [INFO] nonebot_plugin_arktools |         - Skill data already initiated.
10-15 22:37:23 [INFO] nonebot_plugin_arktools |         - Skin data already initiated.
10-15 22:37:23 [INFO] nonebot_plugin_arktools |         - Stage data already initiated.
10-15 22:37:23 [INFO] nonebot_plugin_arktools | ===== ARKNIGHTS-SQLITE DATA ALL INITIATED
10-15 22:37:24 [DEBUG] nonebot | Running PreProcessors...
10-15 22:37:24 [DEBUG] nonebot | Running PostProcessors...
10-15 22:37:29 [DEBUG] nonebot | Running PreProcessors...
10-15 22:37:29 [DEBUG] nonebot | Running PostProcessors...
10-15 22:37:34 [DEBUG] nonebot | Running PreProcessors...
10-15 22:37:34 [DEBUG] nonebot | Running PostProcessors...
10-15 22:37:39 [DEBUG] nonebot | Running PreProcessors...
10-15 22:37:39 [DEBUG] nonebot | Running PostProcessors...
10-15 22:37:44 [DEBUG] nonebot | Running PreProcessors...
10-15 22:37:44 [DEBUG] nonebot | Running PostProcessors...
10-15 22:37:47 [SUCCESS] nonebot | OneBot V11 749411236 | [message.group.normal]: Message 1227811577 from 2407187481@[群:128758348] '/帮助maimaidx'
10-15 22:37:47 [DEBUG] nonebot | Running PreProcessors...
10-15 22:37:47 [DEBUG] nonebot | Checking for matchers in priority 0...
10-15 22:37:47 [DEBUG] nonebot | Checking for matchers in priority 1...
10-15 22:37:47 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_admin.word_analyze, lineno=56)
10-15 22:37:48 [INFO] nonebot | Event will be handled by Matcher(type='message', module=dicergirl, lineno=80)
10-15 22:37:48 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_admin.word_analyze, lineno=56)
10-15 22:37:48 [DEBUG] nonebot | Running handler Dependent(call=_)
10-15 22:37:48 [SUCCESS] nonebot | OneBot V11 749411236 | [message.group.normal]: Message 298266992 from 3202123263@[群:128758348] 'Hx.Bot目前支持的功能：\n（请将UID替换为需要操作的B站UID）\n关闭全体 UID\n开启全体 UID\n关闭动态 UID\n开启动态 UID\n关闭权限\n开启权限\n关闭直播 UID\n开启直播 UID\n已开播\n关注 UID\n取关 UID\n关 注列表\n\n当前版本：v1.6.0post5\n有问题请找3485462167'
10-15 22:37:48 [DEBUG] nonebot | Running PreProcessors...
10-15 22:37:48 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_admin.word_analyze, lineno=56) running complete
10-15 22:37:48 [DEBUG] nonebot | Running Matcher(type='message', module=dicergirl, lineno=80)
10-15 22:37:48 [DEBUG] nonebot | Running handler Dependent(call=loggerhandler)
10-15 22:37:48 [DEBUG] nonebot_plugin_blacklist | 用户 3202123263 在黑名单中, 忽略本次消息
10-15 22:37:48 [INFO] nonebot | Matcher(type='message', module=dicergirl, lineno=80) running complete
10-15 22:37:48 [INFO] nonebot | Event message.group.normal is ignored
10-15 22:37:48 [DEBUG] nonebot | Checking for matchers in priority 2...
10-15 22:37:48 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_admin.auto_ban, lineno=18)
10-15 22:37:48 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_admin.img_check, lineno=16)
10-15 22:37:48 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_admin.auto_ban, lineno=18) running is cancelled
10-15 22:37:48 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_admin.img_check, lineno=16) running is cancelled
10-15 22:37:48 [DEBUG] nonebot | Checking for matchers in priority 3...
10-15 22:37:48 [DEBUG] nonebot | Checking for matchers in priority 4...
10-15 22:37:48 [DEBUG] nonebot | Checking for matchers in priority 5...
10-15 22:37:48 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_maimaidx, lineno=59)
10-15 22:37:48 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_maimaidx, lineno=59)
10-15 22:37:48 [DEBUG] nonebot | Running handler Dependent(call=_)
10-15 22:37:48 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
10-15 22:37:49 [DEBUG] nonebot | Running PreProcessors...
10-15 22:37:49 [DEBUG] nonebot | Running PostProcessors...
10-15 22:37:50 [DEBUG] nonebot | Running CalledAPI hooks...
10-15 22:37:50 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_maimaidx, lineno=59) running complete
10-15 22:37:50 [DEBUG] nonebot | Checking for matchers in priority 6...
10-15 22:37:50 [DEBUG] nonebot | Checking for matchers in priority 10...
10-15 22:37:50 [DEBUG] nonebot | Checking for matchers in priority 11...
10-15 22:37:50 [DEBUG] nonebot | Checking for matchers in priority 12...
10-15 22:37:50 [DEBUG] nonebot | Checking for matchers in priority 13...
10-15 22:37:50 [DEBUG] nonebot | Checking for matchers in priority 14...
10-15 22:37:50 [DEBUG] nonebot | Checking for matchers in priority 15...
10-15 22:37:50 [DEBUG] nonebot | Checking for matchers in priority 20...
10-15 22:37:50 [DEBUG] nonebot | Checking for matchers in priority 24...
10-15 22:37:50 [DEBUG] nonebot | Checking for matchers in priority 27...
10-15 22:37:50 [DEBUG] nonebot | Checking for matchers in priority 30...
10-15 22:37:50 [DEBUG] nonebot | Checking for matchers in priority 50...
10-15 22:37:50 [DEBUG] nonebot | Checking for matchers in priority 60...
10-15 22:37:50 [DEBUG] nonebot | Checking for matchers in priority 80...
10-15 22:37:50 [DEBUG] nonebot | Checking for matchers in priority 90...
10-15 22:37:50 [DEBUG] nonebot | Checking for matchers in priority 99...
10-15 22:37:50 [DEBUG] nonebot | Checking for matchers in priority 100...
10-15 22:37:50 [DEBUG] nonebot | Checking for matchers in priority 999...
10-15 22:37:50 [INFO] nonebot | Event will be handled by Matcher(type='message', module=GenshinUID, lineno=26)
10-15 22:37:50 [DEBUG] nonebot | Running Matcher(type='message', module=GenshinUID, lineno=26)
10-15 22:37:50 [DEBUG] nonebot | Running handler Dependent(call=get_all_message)
10-15 22:37:50 [DEBUG] GenshinUID | [message.group.normal]: Message 1227811577 from 2407187481@[群:128758348] '/帮助maimaidx'
10-15 22:37:50 [INFO] GenshinUID | 【发送】[gsuid-core]: onebot
10-15 22:37:50 [INFO] nonebot | Matcher(type='message', module=GenshinUID, lineno=26) running complete
10-15 22:37:50 [DEBUG] nonebot | Stop event propagation
10-15 22:37:50 [DEBUG] nonebot | Checking for matchers completed
10-15 22:37:50 [DEBUG] nonebot | Running PostProcessors...
10-15 22:37:53 [SUCCESS] nonebot | OneBot V11 749411236 | [notice.notify.poke]: {'time': 1697380673, 'self_id': 749411236, 'post_type': 'notice', 'notice_type': 'notify', 'sub_type': 'poke', 'user_id': 2090176296, 'group_id': 946405200, 'target_id': 2502622085, 'operator_id': 2090176296}
10-15 22:37:53 [DEBUG] nonebot | Running PreProcessors...
10-15 22:37:53 [DEBUG] nonebot | Checking for matchers in priority 0...
10-15 22:37:53 [DEBUG] nonebot | Checking for matchers in priority 1...
10-15 22:37:53 [INFO] nonebot | Event will be handled by Matcher(type='notice', module=nonebot_plugin_antirecall, lineno=184)
10-15 22:37:53 [DEBUG] nonebot | Running Matcher(type='notice', module=nonebot_plugin_antirecall, lineno=184)
10-15 22:37:53 [DEBUG] nonebot | Running handler Dependent(call=recall_handle)
10-15 22:37:53 [DEBUG] nonebot | Handler Dependent(call=recall_handle) skipped
10-15 22:37:53 [INFO] nonebot | Matcher(type='notice', module=nonebot_plugin_antirecall, lineno=184) running complete
10-15 22:37:53 [DEBUG] nonebot | Checking for matchers in priority 2...
10-15 22:37:53 [INFO] nonebot | Event will be handled by Matcher(type='notice', module=nonebot_plugin_blacklist, lineno=230)
10-15 22:37:53 [DEBUG] nonebot | Running Matcher(type='notice', module=nonebot_plugin_blacklist, lineno=230)
10-15 22:37:53 [DEBUG] nonebot | Running handler Dependent(call=_)
10-15 22:37:53 [DEBUG] nonebot | Handler Dependent(call=_) skipped
10-15 22:37:53 [INFO] nonebot | Matcher(type='notice', module=nonebot_plugin_blacklist, lineno=230) running complete
10-15 22:37:53 [DEBUG] nonebot | Checking for matchers in priority 3...
10-15 22:37:53 [DEBUG] nonebot | Checking for matchers in priority 4...
10-15 22:37:53 [DEBUG] nonebot | Checking for matchers in priority 5...
10-15 22:37:53 [DEBUG] nonebot | Checking for matchers in priority 6...
10-15 22:37:53 [DEBUG] nonebot | Checking for matchers in priority 10...
10-15 22:37:53 [DEBUG] nonebot | Checking for matchers in priority 11...
10-15 22:37:53 [DEBUG] nonebot | Checking for matchers in priority 12...
10-15 22:37:54 [DEBUG] nonebot | Checking for matchers in priority 13...
10-15 22:37:54 [DEBUG] nonebot | Checking for matchers in priority 14...
10-15 22:37:54 [DEBUG] nonebot | Checking for matchers in priority 15...
10-15 22:37:54 [DEBUG] nonebot | Checking for matchers in priority 20...
10-15 22:37:54 [DEBUG] nonebot | Checking for matchers in priority 24...
10-15 22:37:54 [DEBUG] nonebot | Checking for matchers in priority 27...
10-15 22:37:54 [DEBUG] nonebot | Checking for matchers in priority 30...
10-15 22:37:54 [DEBUG] nonebot | Checking for matchers in priority 50...
10-15 22:37:54 [DEBUG] nonebot | Checking for matchers in priority 60...
10-15 22:37:54 [DEBUG] nonebot | Checking for matchers in priority 80...
10-15 22:37:54 [DEBUG] nonebot | Checking for matchers in priority 90...
10-15 22:37:54 [DEBUG] nonebot | Checking for matchers in priority 99...
10-15 22:37:54 [DEBUG] nonebot | Checking for matchers in priority 100...
10-15 22:37:54 [DEBUG] nonebot | Checking for matchers in priority 999...
10-15 22:37:54 [INFO] nonebot | Event will be handled by Matcher(type='notice', module=GenshinUID, lineno=27)
10-15 22:37:54 [DEBUG] nonebot | Running Matcher(type='notice', module=GenshinUID, lineno=27)
10-15 22:37:54 [DEBUG] nonebot | Running handler Dependent(call=get_notice_message)
10-15 22:37:54 [DEBUG] GenshinUID | {'time': 1697380673, 'self_id': 749411236, 'post_type': 'notice', 'notice_type': 'notify', 'sub_type': 'poke', 'user_id': 2090176296, 'group_id': 946405200, 'target_id': 2502622085, 'operator_id': 2090176296}
10-15 22:37:54 [INFO] nonebot | Matcher(type='notice', module=GenshinUID, lineno=27) running complete
10-15 22:37:54 [DEBUG] nonebot | Checking for matchers completed
10-15 22:37:54 [DEBUG] nonebot | Running PostProcessors...
10-15 22:37:54 [DEBUG] nonebot | Running PreProcessors...
10-15 22:37:54 [DEBUG] nonebot | Running PostProcessors...

**Comment by ABKQPO** [comment]
建议指定图片的路径

**Comment by Yuri-YuzuChaN** [comment]
已修复该问题，打包未携带到图片，更新一下版本即可
