### ISSUE TITLE
[Feature Request]舞萌2024 ui 更新准备

### ISSUE THREAD

**Issue by SherkeyXD** [Yuri-YuzuChaN/nonebot-plugin-maimaidx#20]
RT
DX2024 确定为 buddies ui 了
是不是可以开始做新版b50主题了（

以及新的b15/b35分割规则

**Comment by Yuri-YuzuChaN** [comment]
在搞了

**Comment by SherkeyXD** [comment]
Update: 由于新版本加了 Sync Play(sync)， 会导致查询 b50 出现 KeyError，需要手动添加 SyncPlay 图表以及 fsl 字典的值
同时需要添加 bud 的 logo，否则 minfo 绘制失败

**Comment by Yuri-YuzuChaN** [comment]
该问题在最新pr已经修复

**Comment by SherkeyXD** [comment]
目前还有一个小问题问题就是没有 `UI_CHR_PlayBonus_SP.png`，带有 SyncPlay 的 `minfo` 查询会失败

**Comment by Yuri-YuzuChaN** [comment]
确实，我重新打包一下

**Comment by Yuri-YuzuChaN** [comment]
已修复
