### ISSUE TITLE
ginfo 功能生成的图片字体是方块

### ISSUE THREAD

**Issue by Apple-QAQ** [Yuri-YuzuChaN/nonebot-plugin-maimaidx#21]
![image](https://github.com/Yuri-YuzuChaN/nonebot-plugin-maimaidx/assets/88485487/72a13549-3537-450d-939b-1df74dd815f0)

如图

**Comment by Yuri-YuzuChaN** [comment]
如果你是 `linux` 的话就不知道了，我这没法测试，字体以及颜色都是固定的，`windows` 是完全正常的

**Comment by Apple-QAQ** [comment]
> 如果你是 `linux` 的话就不知道了，我这没法测试，字体以及颜色都是固定的，`windows` 是完全正常的

好叭，打扰了

**Comment by Yuri-YuzuChaN** [comment]
后续是有打算移除这个功能的，`phantomjs` 毕竟已经停更了

**Comment by Apple-QAQ** [comment]
> 后续是有打算移除这个功能的，`phantomjs` 毕竟已经停更了

这样
