### ISSUE TITLE
定数完成表缺少文件报错

### ISSUE THREAD

**Issue by xiaowww3** [Yuri-YuzuChaN/nonebot-plugin-maimaidx#28]
![image](https://github.com/Yuri-YuzuChaN/nonebot-plugin-maimaidx/assets/84241722/ade69492-3bbe-44db-843a-7b7496f32144)
![image](https://github.com/Yuri-YuzuChaN/nonebot-plugin-maimaidx/assets/84241722/b145fd09-c5c4-4490-a626-963d85467b2c)

**Comment by Yuri-YuzuChaN** [comment]
要自己生成一下定数表，跟bot私聊 `更新定数表`
