### ISSUE TITLE
AttributeError: 'MaiMusic' object has no attribute 'total_list'

### ISSUE THREAD

**Issue by CYDIM** [Yuri-YuzuChaN/nonebot-plugin-maimaidx#29]
如题，所有的有关歌曲的都会AttributeError: 'MaiMusic' object has no attribute 'total_list'
bot显示未知错误：<class'AttributeError'>
![image](https://github.com/Yuri-YuzuChaN/nonebot-plugin-maimaidx/assets/70141670/b57f2574-3612-49a2-bbfb-44e2dfab3002)

**Comment by Yuri-YuzuChaN** [comment]
你是不是没有 `pull`，新版本这个地方是
https://github.com/Yuri-YuzuChaN/nonebot-plugin-maimaidx/blob/7e7d9b6ba883abde951a9459b465f70ee30a80f0/nonebot_plugin_maimaidx/command/mai_base.py#L55

**Comment by CYDIM** [comment]
> 你是不是没有 `pull`，新版本这个地方是
> 
> https://github.com/Yuri-YuzuChaN/nonebot-plugin-maimaidx/blob/7e7d9b6ba883abde951a9459b465f70ee30a80f0/nonebot_plugin_maimaidx/command/mai_base.py#L55

![image](https://github.com/Yuri-YuzuChaN/nonebot-plugin-maimaidx/assets/70141670/8082a94a-e9c2-4639-8ce9-babb5de51bcf)
还是这样

**Comment by Yuri-YuzuChaN** [comment]
你的 `nonebot2` 是什么版本，怎么没有进行获取数据
https://github.com/Yuri-YuzuChaN/nonebot-plugin-maimaidx/blob/7e7d9b6ba883abde951a9459b465f70ee30a80f0/nonebot_plugin_maimaidx/__init__.py#L25-L35

**Comment by Yuri-YuzuChaN** [comment]
这是正常的加载流程
![image](https://github.com/Yuri-YuzuChaN/nonebot-plugin-maimaidx/assets/65105396/70c72825-d99b-4cf4-95f9-1da88703c7d0)

**Comment by CYDIM** [comment]
nonebot2-2.0.0b5

**Comment by CYDIM** [comment]
更新后仍未解决，查分器的开发者Token是必填的吗，我只有这个没写

**Comment by Yuri-YuzuChaN** [comment]
不是必填，你需要找的问题是，为什么没有启动钩子来获取数据，这个只可能是 `nonebot`有问题，要么你重新装依赖，要么把附属依赖都升级了

**Comment by CYDIM** [comment]
![image](https://github.com/Yuri-YuzuChaN/nonebot-plugin-maimaidx/assets/70141670/7e8632f8-72d5-41de-a1e9-af38da450f9b)
都试过了，仍然不行

**Comment by Yuri-YuzuChaN** [comment]
而且你的定时任务也没有启动

**Comment by CYDIM** [comment]
![image](https://github.com/Yuri-YuzuChaN/nonebot-plugin-maimaidx/assets/70141670/46d9846b-8f73-4318-bf03-2bd23e9f0df6)
解决了，换成虚拟环境运行项目就ok了
