### ISSUE TITLE
在初始化启动获取本地暂存别名时出现了TypeError: string indices must be integers, not 'str'

### ISSUE THREAD

**Issue by xydamexy** [Yuri-YuzuChaN/nonebot-plugin-maimaidx#30]
电脑因httpx问题总是在启动时出现获取失败的情况，手动更改了代码（maimaidx_music.py）中301行处
![fortune_data json – E__BOT_YU-BOT_ venv_Lib_site-packages_nonebot_plugin_maimaidx_libraries_maimaidx_music py 2024_6_22 20_05_12](https://github.com/Yuri-YuzuChaN/nonebot-plugin-maimaidx/assets/91752450/135f8861-088b-47b0-a793-c4d9634e8dd4)

但是在获取本地别名时出现了有关python解析json的以下报错
![fortune_data json – E__BOT_YU-BOT_ venv_Lib_site-packages_nonebot_plugin_maimaidx_libraries_maimaidx_music py 2024_6_22 20_07_59](https://github.com/Yuri-YuzuChaN/nonebot-plugin-maimaidx/assets/91752450/9e36cfcb-a639-4d50-804c-700139de1cd6)

**Comment by Yuri-YuzuChaN** [comment]
你的本地别名文件有内容吗

**Comment by xydamexy** [comment]
有的，已经提前获取保存了本地别名文件

**Comment by xydamexy** [comment]
> 你的本地别名文件有内容吗
有点，已经提前获取保存了别名文件

**Comment by xydamexy** [comment]
> 你的本地别名文件有内容吗

有的，已经提前获取保存了别名文件

**Comment by Yuri-YuzuChaN** [comment]
你访问api的时候是不是全选复制的，保存只需要 `content` 字段的内容

**Comment by xydamexy** [comment]
> 你访问api的时候是不是全选复制的，保存只需要 `content` 字段的内容

啊，好的，谢谢，添麻烦了！
