### ISSUE TITLE
所有利用「on_command」匹配 的指令无法识别

### ISSUE THREAD

**Issue by Maotechh** [Yuri-YuzuChaN/nonebot-plugin-maimaidx#37]
# 机器人仅能识别非on_command的指令
![QQ_1722835563814](https://github.com/user-attachments/assets/957b5089-ac2f-4e92-8a3b-0cdba8f8aa68)
![QQ_1722835707956](https://github.com/user-attachments/assets/b2c9bd02-d2ff-4446-acd1-bffddf012074)
![QQ_1722836065684](https://github.com/user-attachments/assets/93f5c952-67eb-4b86-90ad-2f0ab3743da7)

**Comment by Maotechh** [comment]
补充一下，系统ubuntu22.04，运用Lagrange.onebot登陆qq和Nonebot连接。

**Comment by Yuri-YuzuChaN** [comment]
检查所有依赖版本是不是最新，所有指令都经过测试均可使用

**Comment by TTsdzb** [comment]
默认指令前缀导致的

解决方法一：在 `.env.prod` 里加：

```
COMMAND_START=["/", ""]
```

解决方法二：所有不能用的命令在用的时候加 `/`

```diff
- 帮助maimaiDX
+ /帮助maimaiDX
```

**Comment by Maotechh** [comment]
> 默认指令前缀导致的
> 
> 解决方法一：在 `.env.prod` 里加：
> 
> ```
> COMMAND_START=["/", ""]
> ```
> 
> 解决方法二：所有不能用的命令在用的时候加 `/`
> 
> ```diff
> - 帮助maimaiDX
> + /帮助maimaiDX
> ```

你！是对的！！
太感谢你了，这个bug困扰了我好久
