### ISSUE TITLE
Ptyauts

### ISSUE THREAD

**Issue by Ptyauts** [Yuri-YuzuChaN/nonebot-plugin-maimaidx#44]
![cb281547684f4cb8ead33c6d8017688b](https://github.com/user-attachments/assets/b69ebbf2-67b2-4ddb-999d-f8ba716cf2f4)
![1bc0bfe4c55650e2cb40454a06164dfb](https://github.com/user-attachments/assets/f9ab31e9-04a1-407e-9502-632766a0a6b2)
rating文件夹下是空的？
报错的指令是定数表和完成表
看上去这个文件夹下应该有些图片

**Comment by nuym** [comment]
> ![cb281547684f4cb8ead33c6d8017688b](https://github.com/user-attachments/assets/b69ebbf2-67b2-4ddb-999d-f8ba716cf2f4)
> 
> ![1bc0bfe4c55650e2cb40454a06164dfb](https://github.com/user-attachments/assets/f9ab31e9-04a1-407e-9502-632766a0a6b2)
> 
> rating文件夹下是空的？
> 
> 报错的指令是定数表和完成表
> 
> 看上去这个文件夹下应该有些图片

有两个 static文件，一个是更新包，一个是基础，你确定两个下完了么

**Comment by Yuri-YuzuChaN** [comment]
私聊bot指令 `更新定数表`
