### ISSUE TITLE
完成表指令会响应数字

### ISSUE THREAD

**Issue by Xian0Grem** [Yuri-YuzuChaN/nonebot-plugin-maimaidx#46]
有些用户其实想查分数列表但是查成了完成表,然后bot报错了以为我bot又死了🤣
![1c6e7520297fa8e388dbe2db61fad260](https://github.com/user-attachments/assets/d93bbb3b-4fdc-4d02-9807-5d675ad88a09)

**Comment by Yuri-YuzuChaN** [comment]
你得先跟bot私聊一下 `更新完成表` 来生成定数表

**Comment by Xian0Grem** [comment]
更新了还是一样，原来数字完成表是有功能的？
分数列表和牌子完成表功能能用

后台
10-14 17:41:56 [ERROR] nonebot_plugin_maimaidx | Traceback (most recent call last):
  File "F:\NoneBot\BOT\.venv\lib\site-packages\nonebot_plugin_maimaidx\libraries\maimaidx_music_info.py", line 262, in draw_rating_table
    im = Image.open(bg).convert('RGBA')
  File "F:\NoneBot\BOT\.venv\lib\site-packages\PIL\Image.py", line 3431, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\nonebot_ziyuan\\static\\mai\\rating\\13.png'

**Comment by Yuri-YuzuChaN** [comment]
哦，应该是 `更新定数表`，不过版本更新这两个指令都得用

**Comment by Xian0Grem** [comment]
原来如此 用上了,我一直以为数字定数表不是一个功能)

**Comment by Xian0Grem** [comment]
用上了 我以为数字完成表不是指令)
