### ISSUE TITLE
nb run之后显示插件ERROR

### ISSUE THREAD

**Issue by HongXingDeveloper** [Yuri-YuzuChaN/nonebot-plugin-maimaidx#52]
按照开发者的要求，将phantomjs下载并提到了PATH
但插件一开始显示错误，不清楚在哪边出现了问题
![Screenshot_20241125_212324_com_microsoft_rdc_androidx_SessionActivity](https://github.com/user-attachments/assets/5259bf85-72aa-4ae4-80f1-480e255510cd)
![Screenshot_20241125_212250_com_microsoft_rdc_androidx_SessionActivity](https://github.com/user-attachments/assets/588a9670-37ba-46a5-8688-e192f595ef5c)
![Screenshot_20241125_212158_com_microsoft_rdc_androidx_SessionActivity](https://github.com/user-attachments/assets/951c99a6-9990-4ecc-a4e2-2a7141924984)

**Comment by HongXingDeveloper** [comment]
P1是PATH路径
P2是错误报告
P3是在.env中填的内容
谢谢

**Comment by Yuri-YuzuChaN** [comment]
静态文件下了吗

**Comment by HongXingDeveloper** [comment]
静态文件是static吗？已经下了
![Uploading Screenshot_20241125_213709_com_microsoft_rdc_androidx_SessionActivity.jpg…]()

**Comment by Yuri-YuzuChaN** [comment]
看不到图

**Comment by HongXingDeveloper** [comment]
![Screenshot_20241125_214329_com_microsoft_rdc_androidx_SessionActivity](https://github.com/user-attachments/assets/778e8cf1-cb9f-4705-9b87-bb27e063db8e)

**Comment by Yuri-YuzuChaN** [comment]
静态资源路径要到 `\staitc`

**Comment by HongXingDeveloper** [comment]
谢谢您，已经能用了，群友用的很开心
