### ISSUE TITLE
该插件可以在QQ官方机器人中运行吗

### ISSUE THREAD

**Issue by HongXingDeveloper** [Yuri-YuzuChaN/nonebot-plugin-maimaidx#53]
使用了官方机器人后发生错误，想问下是插件问题还是nonebot得问题
![Screenshot_20241126_212709_com_microsoft_rdc_androidx_SessionActivity](https://github.com/user-attachments/assets/fb516ae7-2939-4ffd-b76a-485e91b66b11)

**Comment by Yuri-YuzuChaN** [comment]
插件不支持官方BOT

**Comment by HongXingDeveloper** [comment]
好的，谢谢开发者

**Comment by HongXingDeveloper** [comment]
借步问一下，我在另一个板块看到会适配QQ频道
想知道此插件有可能适配QQ频道吗？（期待）

**Comment by lingdu2333** [comment]
由于插件部分特性 只支持了`OneBot`作为前端 如果你只是需要使用该插件的话可以尝试搭配![Gensokyo](https://github.com/Hoshinonyaruko/Gensokyo)使用

如果真的需要使用`nonebot`的官方QQBot适配器的话可能需要你自行修改代码了（例如官方发送制图后的消息不能图文结合）

**Comment by HongXingDeveloper** [comment]
看完这个插件我大脑都死了😅（虽然没改过插件的代码）
因为目前市面上的QQ官方机器人都是关于这个插件（？）和鹿网
所以就想问问）
