### ISSUE TITLE
pillow版本冲突

### ISSUE THREAD

**Issue by UncleYULE** [Yuri-YuzuChaN/nonebot-plugin-maimaidx#6]

**Comment by Yuri-YuzuChaN** [comment]
冲突？

**Comment by UncleYULE** [comment]
没有 是我的问题，我从来没接触过nonebot和py，部署的时候出了一点小插曲



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月7日(周四) 下午3:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Yuri-YuzuChaN/nonebot-plugin-maimaidx] pillow版本冲突 (Issue #6)




 
冲突？
