### ISSUE TITLE
启动nb无法加载插件

### ISSUE THREAD

**Issue by FangChanguwu** [Yuri-YuzuChaN/nonebot-plugin-maimaidx#7]
![image](https://github.com/Yuri-YuzuChaN/nonebot-plugin-maimaidx/assets/82925556/428c5ef8-abff-4519-b3ae-7c4c17bc9668)

**Comment by Yuri-YuzuChaN** [comment]
忘了py3.8不能用 `Match[str]` 了

**Comment by Yuri-YuzuChaN** [comment]
已修复
