### ISSUE TITLE
Bot不会回复消息

### ISSUE THREAD

**Issue by TTsdzb** [Yuri-YuzuChaN/nonebot-plugin-maimaidx#9]
所有需要回复的地方全部使用了 `reply_message` 参数，但是 `nonebot.matcher.finish` 方法里并没有这个参数。参考 [Nonebot 文档](https://nonebot.dev/docs/api/matcher#Matcher-finish)。

**Comment by TTsdzb** [comment]
回复消息应该是作为一种特殊的消息段存在的，参考[文档](https://nonebot.dev/docs/tutorial/message#%E6%B6%88%E6%81%AF%E6%AE%B5-messagesegment)，需要对不同的平台分别适配。

**Comment by Yuri-YuzuChaN** [comment]
存在该参数，你只是看了该基类的方法，不是各适配器的方法，并且该项目只支持 `onebot-v11` 协议，[Onebot-v11仓库](https://github.com/nonebot/adapter-onebot/blob/ba539a896816375ea8561f28e2f8203f623be401/nonebot/adapters/onebot/v11/bot.py#L136-L143)

**Comment by TTsdzb** [comment]
已证实是 Onebot 软件问题
